<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_LampSetDirect" Id="{c9363aa1-33e3-41da-adea-7faeb59d6855}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC FB_LampSetDirect
VAR
	nLightLevel			: USINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="SetLightLevel" Id="{4b6fea93-5fee-4ee1-8a77-261782e46dcf}">
      <Declaration><![CDATA[// Sets the control value to a value between 0 and 100.
METHOD PUBLIC SetLightLevel
VAR_INPUT
	nNewLightLevel		: USINT(0..100);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[nLightLevel := nNewLightLevel;
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>